# Generated by Django 5.2.7 on 2025-11-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bojang_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='main', max_length=50, unique=True)),
                ('text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
