# Generated by Django 5.2.7 on 2025-10-29 05:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='회사/지점의 IP 주소 (IPv4 또는 IPv6)', unique=True)),
                ('description', models.CharField(blank=True, help_text='설명 (예: 본사, 강남지점)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '회사 IP',
                'verbose_name_plural': '회사 IP 목록',
                'ordering': ['ip_address'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(help_text='로그인한 사용자의 IP 주소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '로그인 기록',
                'verbose_name_plural': '로그인 기록 목록',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('original_filename', models.CharField(help_text='업로드 시 원본 파일명', max_length=512)),
                ('file_size', models.BigIntegerField(default=0, help_text='파일 크기 (bytes)')),
                ('saved_path', models.CharField(help_text='GCS 등 스토리지에 저장된 실제 경로', max_length=1024)),
                ('unmapped_items', models.JSONField(default=list, help_text='매핑에 실패한 항목 리스트')),
                ('excluded_words', models.JSONField(default=list, help_text='분석에서 제외된 단어 리스트')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDF 처리 기록',
                'verbose_name_plural': 'PDF 처리 기록 목록',
                'ordering': ['-processed_at'],
            },
        ),
    ]
